{% set name = "azcopy" %}
{% set version = "10.8.0" %}
{% set release_date = "20201211" %}
{% set sha256 = "8412586abc002cf17e83830795a9f13e18e26d0b1f809441802ae1245ab66e38" %}  # [osx]
{% set sha256 = "c4318d38f8194be41367623472e4ef4576f246cc1ea4cac8637eeda27da07d89" %}  # [linux]
{% set sha256 = "90da52f197e6976e88d7cc1973551600aa918c627b608b156d133b02d11dccda" %}  # [win]
{% set platform = "linux" %}  # [linux]
{% set platform = "darwin" %}    # [osx]
{% set platform = "windows" %}    # [win]
{% set ext = "tar.gz" %}      # [linux]
{% set ext = "zip" %}         # [not linux]


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://azcopyvnext.azureedge.net/release{{ release_date }}/azcopy_{{ platform }}_amd64_{{ version }}.{{ ext }}
  sha256: {{ sha256 }}

build:
  skip: true  # [linux]
  number: 0
  script: "mkdir $PREFIX/bin && cp $SRC_DIR/azcopy $PREFIX/bin/azcopy"  # [not win]
  script: "echo F | xcopy %SRC_DIR%\\azcopy.exe %PREFIX%\\bin\\azcopy.exe /F /Y"  # [win]
  missing_dso_whitelist:
    - "*/libc.so.6"
    - "*/libpthread.so.0"

test:
  commands:
    - azcopy -h

about:
  home: https://github.com/Azure/azure-storage-azcopy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A command-line utility that you can use to copy data to and from containers and file shares in Azure Storage accounts'

  description: |
    AzCopy v10 is a command-line utility that you can use to copy data to and
    from containers and file shares in Azure Storage accounts. AzCopy V10
    presents easy-to-use commands that are optimized for performance.
  doc_url: https://docs.microsoft.com/en-gb/azure/storage/common/storage-use-azcopy-v10
  dev_url: https://github.com/Azure/azure-storage-azcopy

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
