{% set name = "azcopy" %}
{% set version = "10.31.0" %}
{% set sha256 = "abddfeecbddf24682fe2720802002ae5195afc2bd226dcda8e006fbd09f62e4b" %}  # [osx]
{% set sha256 = "1864e3876370186bf81f425b0cc4b67e60341b12035192a37d8b633e19c41fa3" %}  # [linux]
{% set sha256 = "12b93fa3e75ed40fd9fa8417e93ff1358ffa74a272a63fc28c468523bc32ef48" %}  # [win]
{% set platform = "linux" %}  # [linux]
{% set platform = "darwin" %}    # [osx]
{% set platform = "windows" %}    # [win]
{% set ext = "tar.gz" %}      # [linux]
{% set ext = "zip" %}         # [not linux]


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-storage-azcopy/releases/download/v{{ version }}/azcopy_{{ platform }}_amd64_{{ version }}.{{ ext }}
  sha256: {{ sha256 }}

build:
  skip: true  # [not win]
  number: 0
  script: "mkdir $PREFIX/bin && cp $SRC_DIR/azcopy $PREFIX/bin/azcopy"  # [not win]
  script: "echo F | xcopy %SRC_DIR%\\azcopy.exe %PREFIX%\\bin\\azcopy.exe /F /Y"  # [win]
  missing_dso_whitelist:
    - "*/libc.so.6"
    - "*/libpthread.so.0"

test:
  commands:
    - azcopy -h

about:
  home: https://github.com/Azure/azure-storage-azcopy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A command-line utility that you can use to copy data to and from containers and file shares in Azure Storage accounts'

  description: |
    AzCopy v10 is a command-line utility that you can use to copy data to and
    from containers and file shares in Azure Storage accounts. AzCopy V10
    presents easy-to-use commands that are optimized for performance.
  doc_url: https://docs.microsoft.com/en-gb/azure/storage/common/storage-use-azcopy-v10
  dev_url: https://github.com/Azure/azure-storage-azcopy

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
